name: Angular CI/CD
on:
  workflow_run:
    workflows: ["Node.js CI/CD"]
    branches: [master]
    types:
      - completed
env:
  API: wviriya-todo-dev
  STORAGE_ACCOUNT: wviriyatododevapp
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
                
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "${API}"
          replace: ${{ env.API }}
          include: "environment.prod.ts" # Will match all README.md files in any nested directory
        
      - name: npm install and npm run build
        run: |
          cd $GITHUB_WORKSPACE/angular-app
          npm install --save-dev @angular-devkit/build-angular
          npm install -g @angular/cli
          ng build --prod
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI - Publish Static Website
        uses: Azure/cli@v1.0.0
        with:
          # Specify the script here
          inlineScript: az storage blob upload-batch -s $GITHUB_WORKSPACE/angular-app/dist/angular-app -d '$web' --account-name ${{ env.STORAGE_ACCOUNT }}  
